package com.product.demo.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.product.demo.greendao.bean.EditInfo;

import com.product.demo.greendao.dao.EditInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig editInfoDaoConfig;

    private final EditInfoDao editInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        editInfoDaoConfig = daoConfigMap.get(EditInfoDao.class).clone();
        editInfoDaoConfig.initIdentityScope(type);

        editInfoDao = new EditInfoDao(editInfoDaoConfig, this);

        registerDao(EditInfo.class, editInfoDao);
    }
    
    public void clear() {
        editInfoDaoConfig.getIdentityScope().clear();
    }

    public EditInfoDao getEditInfoDao() {
        return editInfoDao;
    }

}
