package com.product.demo.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EDIT_INFO".
 */
public class EditInfo {

    private long id;
    private String userId;
    private String alarmSituationId;
    private String handleInfo;
    private String surveyInfo;

    public EditInfo() {
    }

    public EditInfo(long id) {
        this.id = id;
    }

    public EditInfo(long id, String userId, String alarmSituationId, String handleInfo, String surveyInfo) {
        this.id = id;
        this.userId = userId;
        this.alarmSituationId = alarmSituationId;
        this.handleInfo = handleInfo;
        this.surveyInfo = surveyInfo;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAlarmSituationId() {
        return alarmSituationId;
    }

    public void setAlarmSituationId(String alarmSituationId) {
        this.alarmSituationId = alarmSituationId;
    }

    public String getHandleInfo() {
        return handleInfo;
    }

    public void setHandleInfo(String handleInfo) {
        this.handleInfo = handleInfo;
    }

    public String getSurveyInfo() {
        return surveyInfo;
    }

    public void setSurveyInfo(String surveyInfo) {
        this.surveyInfo = surveyInfo;
    }

}
