package com.product.demo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.product.demo.greendao.entity.BarCode;
import com.product.demo.greendao.entity.User;

import com.product.demo.greendao.BarCodeDao;
import com.product.demo.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig barCodeDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BarCodeDao barCodeDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        barCodeDaoConfig = daoConfigMap.get(BarCodeDao.class).clone();
        barCodeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        barCodeDao = new BarCodeDao(barCodeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BarCode.class, barCodeDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        barCodeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BarCodeDao getBarCodeDao() {
        return barCodeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
