package com.product.demo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.product.demo.greendao.entity.Assets;
import com.product.demo.greendao.entity.BarCode;
import com.product.demo.greendao.entity.User;

import com.product.demo.greendao.AssetsDao;
import com.product.demo.greendao.BarCodeDao;
import com.product.demo.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig assetsDaoConfig;
    private final DaoConfig barCodeDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AssetsDao assetsDao;
    private final BarCodeDao barCodeDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        assetsDaoConfig = daoConfigMap.get(AssetsDao.class).clone();
        assetsDaoConfig.initIdentityScope(type);

        barCodeDaoConfig = daoConfigMap.get(BarCodeDao.class).clone();
        barCodeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        assetsDao = new AssetsDao(assetsDaoConfig, this);
        barCodeDao = new BarCodeDao(barCodeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Assets.class, assetsDao);
        registerDao(BarCode.class, barCodeDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        assetsDaoConfig.clearIdentityScope();
        barCodeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AssetsDao getAssetsDao() {
        return assetsDao;
    }

    public BarCodeDao getBarCodeDao() {
        return barCodeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
